echo "Starting t5 scripts..."
cd t5
screen -dm bash -c "CUDA_VISIBLE_DEVICES=0 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5hint --hints  --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --gradient_accumulation_steps 4 --do_train "
screen -dm bash -c "CUDA_VISIBLE_DEVICES=1 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5hint1 --hints  --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --gradient_accumulation_steps 4 --do_train "
screen -dm bash -c "CUDA_VISIBLE_DEVICES=2 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5hint2 --hints  --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --do_train  --gradient_accumulation_steps 4"
screen -dm bash -c "CUDA_VISIBLE_DEVICES=3 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5hint3 --hints  --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --do_train --gradient_accumulation_steps 4"

screen -dm bash -c "CUDA_VISIBLE_DEVICES=0 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5nohint   --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --do_train --gradient_accumulation_steps 4"
screen -dm bash -c "CUDA_VISIBLE_DEVICES=1 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5nohint1   --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --do_train --gradient_accumulation_steps 4"
screen -dm bash -c "CUDA_VISIBLE_DEVICES=2 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5nohint2   --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --do_train --gradient_accumulation_steps 4"
screen -dm bash -c "CUDA_VISIBLE_DEVICES=3 /u/pe25171/anaconda3/envs/hinting/bin/python finetune_hints.py --model_name_or_path t5-base --train_file ../../data/t5_training_data_all.json --text_column source --summary_column target --output_dir t5nohint3   --do_test --tokenizer_name t5-base --num_train_epochs 5 --num_warmup_steps 3000 --learning_rate 3e-4 --per_device_eval_batch_size 4 --per_device_train_batch_size 4 --do_train --gradient_accumulation_steps 4"
